"""Focused adversarial tests for the frozen primary role-manifest contract.

The fixture deliberately lives under an isolated temporary study root.  It
copies only the frozen protocol and the three role-contract schemas, creates
content-addressed stand-ins for every pre-primary root asset, and builds a
complete eight-role execution DAG.  No real holdout case or real combined seal
is read or generated by this test.
"""

from __future__ import annotations

import copy
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Mapping


TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from validate_primary_holdout_protocol import (  # noqa: E402
    ProtocolError,
    validate_role_manifest,
    validate_role_manifest_set,
)


SOURCE_STUDY_ROOT = Path(__file__).resolve().parents[2]
PROTOCOL_REL = "holdout/PRIMARY_HOLDOUT_EXECUTION_PROTOCOL_v1.json"
ROLE_SCHEMA_REL = "holdout/schemas/primary_role_execution_manifest.schema.json"
ROLE_SET_SCHEMA_REL = "holdout/schemas/primary_role_manifest_set.schema.json"
TRACE_SCHEMA_REL = "holdout/schemas/primary_role_tool_access_trace.schema.json"
SANITIZED_RUNTIME_SCHEMA_REL = "holdout/schemas/evaluator_sanitized_runtime_ledger.schema.json"
ALL_SEALED_REPLAY_SCHEMA_REL = (
    "holdout/schemas/primary_all_sealed_artifacts_after_replay.schema.json"
)
SEALED_CONCEPT_MAP_SCHEMA_REL = "holdout/schemas/sealed_concept_map.schema.json"
SANITIZED_COMPILER_INPUT_SCHEMA_REL = (
    "holdout/schemas/evaluator_sanitized_runtime_ledger_compiler_input.schema.json"
)
SANITIZED_ASSIGNMENT_PROOF_SCHEMA_REL = (
    "holdout/schemas/evaluator_sanitized_runtime_ledger_assignment_proof.schema.json"
)
SANITIZED_REPLAY_VERIFICATION_SCHEMA_REL = (
    "holdout/schemas/evaluator_sanitized_runtime_ledger_replay_verification.schema.json"
)
SANITIZED_COMPILER_REL = (
    "holdout/tools/compile_evaluator_sanitized_runtime_ledger.py"
)
SANITIZED_COMPILER_TEST_REL = (
    "holdout/tools/test_compile_evaluator_sanitized_runtime_ledger.py"
)
SANITIZED_REPLAY_VERIFIER_REL = (
    "holdout/tools/verify_evaluator_sanitized_runtime_ledger.py"
)
SANITIZED_REPLAY_VERIFIER_TEST_REL = (
    "holdout/tools/test_verify_evaluator_sanitized_runtime_ledger.py"
)
PRODUCER_REPLAY_VERIFIER_REL = "holdout/tools/producer_replay_verifier.py"
_UNSET = object()


def _canonical_sha(value: Mapping[str, Any]) -> str:
    payload = json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


class _RoleContractFixture:
    """Complete content-addressed primary-role run in an isolated study root."""

    def __init__(
        self,
        root: Path,
        *,
        malicious_sanitized_canonical: str | None = None,
        omit_all_sealed_inventory_class: str | None = None,
        sanitized_unit: Any = _UNSET,
        use_legacy_absolute_times: bool = False,
        sanitized_event_kind: str = "OBSERVATION",
        include_action_lifecycle: bool = False,
        action_lifecycle_phase: str = "STARTED",
        action_lifecycle_sequence: list[tuple[int, str]] | None = None,
        action_dose_canonical: str = "1",
        action_dose_unit: Any = _UNSET,
        omit_action_dose_fields: bool = False,
        force_action_dose_fields: bool = False,
        omit_evidence_qualification_field: str | None = None,
        evidence_qualification_override: Mapping[str, Any] | None = None,
        include_alternative_representation_group: bool = True,
        alternative_representation_group_id: Any = None,
        sealed_mapping_unit_override: Any = _UNSET,
        sanitized_ledger_extra: Mapping[str, Any] | None = None,
        observed_epoch_ordinal: int = 0,
        available_epoch_ordinal: int = 0,
        opaque_run_id_override: str | None = None,
        opaque_event_id_override: str | None = None,
        opaque_source_concept_token_override: str | None = None,
        opaque_action_id_override: str | None = None,
    ) -> None:
        self.root = root
        self.malicious_sanitized_canonical = malicious_sanitized_canonical
        self.omit_all_sealed_inventory_class = omit_all_sealed_inventory_class
        self.sanitized_unit = (
            ("percent" if sanitized_event_kind == "OBSERVATION" else None)
            if sanitized_unit is _UNSET
            else sanitized_unit
        )
        self.use_legacy_absolute_times = use_legacy_absolute_times
        self.sanitized_event_kind = sanitized_event_kind
        self.include_action_lifecycle = include_action_lifecycle
        self.action_lifecycle_phase = action_lifecycle_phase
        self.action_lifecycle_sequence = action_lifecycle_sequence
        self.action_dose_canonical = action_dose_canonical
        self.action_dose_unit = None if action_dose_unit is _UNSET else action_dose_unit
        self.omit_action_dose_fields = omit_action_dose_fields
        self.force_action_dose_fields = force_action_dose_fields
        self.omit_evidence_qualification_field = omit_evidence_qualification_field
        self.evidence_qualification_override = evidence_qualification_override
        self.include_alternative_representation_group = (
            include_alternative_representation_group
        )
        self.alternative_representation_group_id = alternative_representation_group_id
        self.sealed_mapping_unit_override = sealed_mapping_unit_override
        self.sanitized_ledger_extra = sanitized_ledger_extra
        self.observed_epoch_ordinal = observed_epoch_ordinal
        self.available_epoch_ordinal = available_epoch_ordinal
        self.opaque_run_id_override = opaque_run_id_override
        self.opaque_event_id_override = opaque_event_id_override
        self.opaque_source_concept_token_override = opaque_source_concept_token_override
        self.opaque_action_id_override = opaque_action_id_override
        self.protocol_path = self.root / PROTOCOL_REL
        self.aggregate_path = self.root / "run/role_manifest_set.json"
        self.manifest_paths: dict[str, Path] = {}
        self.output_by_class: dict[str, dict[str, Any]] = {}
        self._copy_contract_files()
        self.protocol = self.read_json(self.protocol_path)
        self.roles = list(self.protocol["role_manifest"]["required_roles"])
        self.schema_ids = dict(self.protocol["role_manifest"]["data_class_schema_ids"])
        self.root_paths = dict(self.protocol["role_manifest"]["presealed_root_asset_paths"])
        self.root_classes = set(self.protocol["role_manifest"]["presealed_root_data_classes"])
        self._create_presealed_roots_and_mock_seal()
        self._create_complete_role_dag()

    def _copy_contract_files(self) -> None:
        for rel in (
            PROTOCOL_REL,
            ROLE_SCHEMA_REL,
            ROLE_SET_SCHEMA_REL,
            TRACE_SCHEMA_REL,
            SANITIZED_RUNTIME_SCHEMA_REL,
            ALL_SEALED_REPLAY_SCHEMA_REL,
            SEALED_CONCEPT_MAP_SCHEMA_REL,
            SANITIZED_COMPILER_INPUT_SCHEMA_REL,
            SANITIZED_ASSIGNMENT_PROOF_SCHEMA_REL,
            SANITIZED_REPLAY_VERIFICATION_SCHEMA_REL,
            SANITIZED_COMPILER_REL,
            SANITIZED_COMPILER_TEST_REL,
            SANITIZED_REPLAY_VERIFIER_REL,
            SANITIZED_REPLAY_VERIFIER_TEST_REL,
            PRODUCER_REPLAY_VERIFIER_REL,
        ):
            source = SOURCE_STUDY_ROOT / rel
            target = self.root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            if source.is_file():
                shutil.copy2(source, target)
            else:
                target.write_text(
                    "# isolated frozen compiler fixture placeholder\n", encoding="utf-8"
                )

    @staticmethod
    def read_json(path: Path) -> dict[str, Any]:
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise AssertionError(f"fixture expected object: {path}")
        return value

    def rel(self, path: Path) -> str:
        return path.relative_to(self.root).as_posix()

    def ref(self, path: Path) -> dict[str, Any]:
        payload = path.read_bytes()
        return {
            "path": self.rel(path),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "bytes": len(payload),
        }

    def artifact(
        self,
        path: Path,
        data_class: str,
        *,
        producer: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        row = {
            **self.ref(path),
            "data_class": data_class,
            "schema_id": self.schema_ids[data_class],
        }
        if producer is not None:
            row["producer"] = copy.deepcopy(dict(producer))
        return row

    def _create_presealed_roots_and_mock_seal(self) -> None:
        # Create every exact frozen root path except the combined seal itself.
        root_rows: list[dict[str, Any]] = []
        for data_class, rel in self.root_paths.items():
            if data_class == "combined_preprimary_seal":
                continue
            path = self.root / rel
            if rel == PROTOCOL_REL:
                # Already copied verbatim above.
                pass
            elif data_class in {
                "sanitized_id_type_unit_registry",
                "sanitized_process_name_description_registry",
                "model_pack",
            }:
                path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(SOURCE_STUDY_ROOT / rel, path)
            elif path.suffix.lower() == ".md":
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(
                    f"# Isolated fixture asset: {data_class}\n", encoding="utf-8"
                )
            else:
                _write_json(
                    path,
                    {
                        "fixture": "primary-role-contract-hardening",
                        "data_class": data_class,
                    },
                )
            root_rows.append(
                {"data_class": data_class, "artifact": self.ref(path)}
            )

        seal_path = self.root / self.root_paths["combined_preprimary_seal"]
        unsigned_seal: dict[str, Any] = {
            "format_version": "NCF-PRE-PRIMARY-HOLDOUT-SEAL-1.0.0",
            "seal_id": "NCF-PRE-PRIMARY-HOLDOUT-SEAL",
            "status": "SEALED_BEFORE_PRIMARY_CASE_SELECTION",
            "case_blindness": {
                "case_content_read_by_builder": False,
                "case_identity_selected": False,
            },
            "fixture_presealed_root_artifacts": root_rows,
            "fixture_frozen_sanitizer_assets": [
                self.ref(self.root / rel)
                for rel in (
                    SANITIZED_COMPILER_REL,
                    SANITIZED_COMPILER_TEST_REL,
                    SANITIZED_COMPILER_INPUT_SCHEMA_REL,
                    SANITIZED_RUNTIME_SCHEMA_REL,
                    SANITIZED_ASSIGNMENT_PROOF_SCHEMA_REL,
                )
            ],
            "bindings": {
                "primary_execution": {
                    "evaluator_sanitized_runtime_ledger_compiler": self.ref(
                        self.root / SANITIZED_COMPILER_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_compiler_test": self.ref(
                        self.root / SANITIZED_COMPILER_TEST_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_compiler_input_schema": self.ref(
                        self.root / SANITIZED_COMPILER_INPUT_SCHEMA_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_schema": self.ref(
                        self.root / SANITIZED_RUNTIME_SCHEMA_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_assignment_proof_schema": self.ref(
                        self.root / SANITIZED_ASSIGNMENT_PROOF_SCHEMA_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_replay_verifier": self.ref(
                        self.root / SANITIZED_REPLAY_VERIFIER_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_replay_verifier_test": self.ref(
                        self.root / SANITIZED_REPLAY_VERIFIER_TEST_REL
                    ),
                    "evaluator_sanitized_runtime_ledger_replay_verification_schema": self.ref(
                        self.root / SANITIZED_REPLAY_VERIFICATION_SCHEMA_REL
                    ),
                    "producer_replay_verifier": self.ref(
                        self.root / PRODUCER_REPLAY_VERIFIER_REL
                    ),
                }
            },
        }
        seal = dict(unsigned_seal)
        seal["payload_sha256"] = _canonical_sha(unsigned_seal)
        self.combined_seal_payload_sha256 = seal["payload_sha256"]
        _write_json(seal_path, seal)
        self.seal_ref = self.ref(seal_path)

    def _root_input(self, data_class: str) -> dict[str, Any]:
        return self.artifact(
            self.root / self.root_paths[data_class],
            data_class,
            producer={"kind": "PRESEALED_ROOT", "seal": self.seal_ref},
        )

    def _upstream_input(self, data_class: str) -> dict[str, Any]:
        produced = self.output_by_class[data_class]
        artifact_row = copy.deepcopy(produced["artifact"])
        manifest_ref = self.ref(produced["manifest_path"])
        artifact_row["producer"] = {
            "kind": "ROLE_OUTPUT",
            "role": produced["role"],
            "run_id": produced["run_id"],
            "manifest_path": manifest_ref["path"],
            "manifest_sha256": manifest_ref["sha256"],
            "manifest_bytes": manifest_ref["bytes"],
        }
        return artifact_row

    def _trace_accesses(
        self,
        inputs: list[dict[str, Any]],
        outputs: list[dict[str, Any]],
        prompt_ref: Mapping[str, Any],
        parent_ref: Mapping[str, Any],
    ) -> list[dict[str, Any]]:
        accesses: list[dict[str, Any]] = []

        def append(
            operation: str,
            artifact_kind: str,
            row: Mapping[str, Any],
            data_class: str,
            schema_id: str,
        ) -> None:
            accesses.append(
                {
                    "sequence": len(accesses),
                    "operation": operation,
                    "artifact_kind": artifact_kind,
                    "path": row["path"],
                    "sha256": row["sha256"],
                    "bytes": row["bytes"],
                    "data_class": data_class,
                    "schema_id": schema_id,
                    "access_count": 1,
                }
            )

        for row in inputs:
            append("READ", "INPUT", row, row["data_class"], row["schema_id"])
        for row in outputs:
            append("WRITE", "OUTPUT", row, row["data_class"], row["schema_id"])
        append(
            "READ",
            "PROMPT_OR_COMMAND",
            prompt_ref,
            "role_prompt_or_command",
            "ncf.role.prompt-or-command.v1",
        )
        append(
            "READ",
            "PARENT_PACKET",
            parent_ref,
            "role_parent_packet",
            "ncf.role.parent-packet.v1",
        )
        return accesses

    def _sanitized_ledger_payload(self) -> dict[str, Any]:
        lifecycle_sequence = self.action_lifecycle_sequence
        if lifecycle_sequence is None:
            lifecycle_sequence = [
                (self.observed_epoch_ordinal, self.action_lifecycle_phase)
            ]
        events: list[dict[str, Any]] = []
        for event_index, (observed_ordinal, lifecycle_phase) in enumerate(
            lifecycle_sequence
        ):
            is_action = self.sanitized_event_kind in {"ACTION", "SUPPORT"}
            event: dict[str, Any] = {
                "opaque_event_id": (
                    self.opaque_event_id_override
                    if event_index == 0 and self.opaque_event_id_override is not None
                    else f"EV-{event_index + 1:08d}"
                ),
                "opaque_source_concept_token": (
                    self.opaque_source_concept_token_override or "SC-00000001"
                ),
                "event_kind": self.sanitized_event_kind,
                "typed_value": (
                    {"kind": "CODE", "canonical": self.malicious_sanitized_canonical}
                    if self.malicious_sanitized_canonical is not None
                    else (
                        {"kind": "CODE", "canonical": lifecycle_phase}
                        if is_action
                        else {"kind": "NUMBER", "canonical": "1"}
                    )
                ),
                "unit": self.sanitized_unit,
                "reliability": "HIGH",
            }
            if self.use_legacy_absolute_times:
                event.update(
                    {
                        "observed_at": "2026-07-21T00:00:00+09:00",
                        "available_at": "2026-07-21T00:00:00+09:00",
                    }
                )
            else:
                event.update(
                    {
                        "observed_epoch_ordinal": observed_ordinal,
                        "available_epoch_ordinal": (
                            self.available_epoch_ordinal
                            if self.action_lifecycle_sequence is None
                            else observed_ordinal
                        ),
                    }
                )
            if self.include_action_lifecycle or self.action_lifecycle_sequence is not None:
                lifecycle: dict[str, Any] = {
                    "opaque_action_id": self.opaque_action_id_override or "ACT-00000001",
                    "phase": lifecycle_phase,
                }
                if (
                    lifecycle_phase in {
                        "STARTED", "CONTINUED", "DOSE_CHANGED", "RESUMED",
                    }
                    or self.force_action_dose_fields
                ) and not self.omit_action_dose_fields:
                    lifecycle.update(
                        {
                            "dose": {
                                "kind": "NUMBER",
                                "canonical": self.action_dose_canonical,
                            },
                            "dose_unit": self.action_dose_unit,
                        }
                    )
                event["action_lifecycle"] = lifecycle
            if self.sanitized_event_kind == "OBSERVATION":
                qualification: dict[str, Any] = {
                    "explicit_assertion": "TRUE",
                    "target_scope": "TRUE",
                    "adequate_method": "TRUE",
                    "adequate_timing": "TRUE",
                    "adequate_reliability": "TRUE",
                }
                if self.evidence_qualification_override is not None:
                    qualification.update(self.evidence_qualification_override)
                if self.omit_evidence_qualification_field is not None:
                    qualification.pop(self.omit_evidence_qualification_field, None)
                event["evidence_qualification"] = qualification
                if self.include_alternative_representation_group:
                    event["alternative_representation_group_id"] = (
                        self.alternative_representation_group_id
                    )
            events.append(event)
        payload: dict[str, Any] = {
            "schema_version": "NCF-EVALUATOR-SANITIZED-RUNTIME-LEDGER-1.0.0",
            "opaque_run_id": (
                self.opaque_run_id_override
                or f"RUN-{self.combined_seal_payload_sha256}"
            ),
            "identity_removed": True,
            "source_text_removed": True,
            "source_locator_removed": True,
            "reversible_source_ids_removed": True,
            "events": events,
        }
        if self.sanitized_ledger_extra is not None:
            payload.update(self.sanitized_ledger_extra)
        return payload

    def _source_ledgers_for_compiler(self) -> tuple[dict[str, Any], dict[str, Any]]:
        """Reverse the desired transport rows into source-rich compiler inputs.

        Canonical opaque ids are intentionally *not* copied backwards.  The
        frozen compiler must assign them.  Invalid/mutated transport fixtures
        may fail this reverse path and fall back to hand-authored artifacts;
        every positive fixture must take the real compiler + verifier path.
        """

        target = self._sanitized_ledger_payload()
        source_events: list[dict[str, Any]] = []
        availability_events: list[dict[str, Any]] = []
        for index, event in enumerate(target["events"], start=1):
            source_event_id = f"source-event-{index:08d}"
            observed = event.get("observed_epoch_ordinal", 0)
            available = event.get("available_epoch_ordinal", observed)
            runtime_event: dict[str, Any] = {
                "source_concept_token": "source-concept-00000001",
                "event_kind": event["event_kind"],
                "typed_value": copy.deepcopy(event["typed_value"]),
                "unit": copy.deepcopy(event["unit"]),
                "observed_epoch_ordinal": observed,
                "reliability": event["reliability"],
            }
            lifecycle = event.get("action_lifecycle")
            if isinstance(lifecycle, Mapping):
                source_lifecycle = {
                    key: copy.deepcopy(value)
                    for key, value in lifecycle.items()
                    if key != "opaque_action_id"
                }
                source_lifecycle["source_action_instance_id"] = (
                    "source-action-00000001"
                )
                runtime_event["action_lifecycle"] = source_lifecycle
            if event["event_kind"] == "OBSERVATION":
                if "evidence_qualification" in event:
                    runtime_event["evidence_qualification"] = copy.deepcopy(
                        event["evidence_qualification"]
                    )
                if "alternative_representation_group_id" in event:
                    runtime_event["source_alternative_representation_group_id"] = (
                        "source-group-00000001"
                        if event["alternative_representation_group_id"] is not None
                        else None
                    )
            source_events.append(
                {
                    "source_event_id": source_event_id,
                    "runtime_event": runtime_event,
                }
            )
            availability_events.append(
                {
                    "source_event_id": source_event_id,
                    "availability_evidence": {
                        "kind": "EXACT",
                        "exact_epoch": available,
                    },
                }
            )
        return (
            {
                "schema_version": "ncf.data.sealed-event-ledger.v1",
                "events": source_events,
            },
            {
                "schema_version": "ncf.data.sealed-availability-ledger.v1",
                "events": availability_events,
            },
        )

    @staticmethod
    def _typed_ref(row: Mapping[str, Any]) -> dict[str, Any]:
        return {
            key: row[key]
            for key in ("path", "sha256", "bytes", "data_class", "schema_id")
        }

    def _create_external_sanitized_ledger(self) -> None:
        external_dir = self.root / "run" / "external_sanitizer"
        external_dir.mkdir(parents=True, exist_ok=True)
        ledger_path = external_dir / "evaluator_sanitized_runtime_ledger.json"
        ledger_payload = self._sanitized_ledger_payload()

        slots = [
            "sealed_event_ledger",
            "sealed_availability_ledger",
            "sealed_concept_map",
            "sanitized_id_type_unit_registry",
            "combined_preprimary_seal",
        ]
        input_rows: dict[str, dict[str, Any]] = {}
        for slot in slots:
            if slot in {"sanitized_id_type_unit_registry", "combined_preprimary_seal"}:
                input_rows[slot] = self._typed_ref(self._root_input(slot))
            else:
                input_rows[slot] = self._typed_ref(
                    self.output_by_class[slot]["artifact"]
                )
        manifest_path = external_dir / "compiler_input_manifest.json"
        _write_json(
            manifest_path,
            {
                "schema_version": (
                    "NCF-EVALUATOR-SANITIZED-RUNTIME-LEDGER-COMPILER-INPUT-1.0.0"
                ),
                "inputs": input_rows,
            },
        )

        digest_events: list[dict[str, Any]] = []
        source_tokens: set[str] = set()
        action_ids: set[str] = set()
        alternative_groups: set[str] = set()
        for event in ledger_payload["events"]:
            source_tokens.add(event["opaque_source_concept_token"])
            lifecycle = event.get("action_lifecycle")
            action_id = (
                lifecycle.get("opaque_action_id")
                if isinstance(lifecycle, Mapping)
                else None
            )
            if action_id is not None:
                action_ids.add(action_id)
            alternative_group = event.get("alternative_representation_group_id")
            if alternative_group is not None:
                alternative_groups.add(alternative_group)
            digest_events.append(
                {
                    "opaque_event_id": event["opaque_event_id"],
                    "opaque_source_concept_token": event[
                        "opaque_source_concept_token"
                    ],
                    "opaque_action_id": action_id,
                    "alternative_representation_group_id": alternative_group,
                }
            )
        proof_path = (
            external_dir
            / "evaluator_sanitized_runtime_ledger_assignment_proof.json"
        )
        compiler_run = subprocess.run(
            [
                sys.executable,
                str(self.root / SANITIZED_COMPILER_REL),
                "compile",
                "--study-root",
                str(self.root),
                "--manifest",
                str(manifest_path),
                "--output-ledger",
                str(ledger_path),
                "--assignment-proof",
                str(proof_path),
            ],
            cwd=self.root,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        compiler_succeeded = (
            compiler_run.returncode == 0
            and ledger_path.is_file()
            and proof_path.is_file()
            and self.read_json(ledger_path) == ledger_payload
        )
        if not compiler_succeeded:
            ledger_path.unlink(missing_ok=True)
            proof_path.unlink(missing_ok=True)
            _write_json(ledger_path, ledger_payload)
        ledger_artifact = self.artifact(
            ledger_path, "evaluator_sanitized_runtime_ledger"
        )
        frozen_asset_spec = [
            ("compiler", SANITIZED_COMPILER_REL),
            ("compiler_test", SANITIZED_COMPILER_TEST_REL),
            ("compiler_input_schema", SANITIZED_COMPILER_INPUT_SCHEMA_REL),
            ("ledger_output_schema", SANITIZED_RUNTIME_SCHEMA_REL),
            ("assignment_proof_schema", SANITIZED_ASSIGNMENT_PROOF_SCHEMA_REL),
        ]
        proof = {
            "schema_version": (
                "NCF-EVALUATOR-SANITIZED-RUNTIME-LEDGER-ASSIGNMENT-PROOF-1.0.0"
            ),
            "producer_id": "evaluator-sanitized-runtime-ledger-compiler-v1",
            "status": "PASS",
            "input_manifest": self.ref(manifest_path),
            "inputs": [
                {"slot": slot, **input_rows[slot]} for slot in slots
            ],
            "output_ledger": {
                "path": "evaluator_sanitized_runtime_ledger.json",
                **{
                    key: ledger_artifact[key]
                    for key in ("sha256", "bytes", "data_class", "schema_id")
                },
            },
            "frozen_assets": [
                {"asset_role": role, **self.ref(self.root / rel)}
                for role, rel in frozen_asset_spec
            ],
            "combined_preprimary_seal_payload_sha256": (
                self.combined_seal_payload_sha256
            ),
            "opaque_run_id": ledger_payload["opaque_run_id"],
            "assignment_algorithm": {
                "run_id": "RUN_PREFIX_PLUS_FULL_COMBINED_PREPRIMARY_PAYLOAD_SHA256",
                "event_id": "CANONICAL_LEDGER_ROW_ORDER_DECIMAL8_START1",
                "source_concept_id": (
                    "CANONICAL_LEDGER_FIRST_OCCURRENCE_DECIMAL8_START1"
                ),
                "action_id": "CANONICAL_LEDGER_FIRST_OCCURRENCE_DECIMAL8_START1",
                "alternative_group_id": (
                    "CANONICAL_LEDGER_FIRST_OCCURRENCE_DECIMAL8_START1"
                ),
            },
            "assignment_counts": {
                "events": len(ledger_payload["events"]),
                "source_concepts": len(source_tokens),
                "actions": len(action_ids),
                "alternative_groups": len(alternative_groups),
            },
            "assignment_digest": _canonical_sha(
                {
                    "opaque_run_id": ledger_payload["opaque_run_id"],
                    "events": digest_events,
                }
            ),
        }
        if not compiler_succeeded:
            _write_json(proof_path, proof)
        else:
            proof = self.read_json(proof_path)

        verification_path = external_dir / "replay_verification.json"
        if compiler_succeeded:
            verifier_run = subprocess.run(
                [
                    sys.executable,
                    str(self.root / SANITIZED_REPLAY_VERIFIER_REL),
                    "verify",
                    "--study-root",
                    str(self.root),
                    "--manifest",
                    str(manifest_path),
                    "--ledger",
                    str(ledger_path),
                    "--assignment-proof",
                    str(proof_path),
                    "--combined-seal",
                    str(self.root / self.root_paths["combined_preprimary_seal"]),
                    "--output",
                    str(verification_path),
                ],
                cwd=self.root,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
            if verifier_run.returncode != 0 or not verification_path.is_file():
                raise AssertionError(
                    "positive sanitizer fixture failed independent fresh replay: "
                    f"stdout={verifier_run.stdout!r} stderr={verifier_run.stderr!r}"
                )
        else:
            # Invalid transport fixtures are expected to fail before replay.
            # Keep a schema-valid but non-authoritative placeholder so the
            # manifest shape itself does not mask the intended validation
            # error.  No positive fixture may take this branch.
            _write_json(
                verification_path,
                {
                    "schema_version": (
                        "NCF-EVALUATOR-SANITIZED-RUNTIME-LEDGER-REPLAY-VERIFICATION-1.0.0"
                    ),
                    "produced_by": SANITIZED_REPLAY_VERIFIER_REL,
                    "producer_id": (
                        "evaluator-sanitized-runtime-ledger-compiler-v1"
                    ),
                    "status": "PASS",
                    "verifier_tool": self.ref(
                        self.root / SANITIZED_REPLAY_VERIFIER_REL
                    ),
                    "compiler_tool": self.ref(self.root / SANITIZED_COMPILER_REL),
                    "compiler_input_manifest": self.ref(manifest_path),
                    "compiler_outputs": {
                        "ledger": self.ref(ledger_path),
                        "assignment_proof": self.ref(proof_path),
                    },
                    "combined_preprimary_seal_payload_sha256": (
                        self.combined_seal_payload_sha256
                    ),
                    "replay_policy_sha256": "0" * 64,
                    "replay_claim": {
                        "adapter_id": "CONFIGURED_CLI_EXACT_JSON_V1",
                        "input_ref_ids": {
                            "input_manifest": "compiler-input-manifest"
                        },
                        "output_ref_ids": {
                            "ledger": "sanitized-ledger",
                            "assignment_proof": "assignment-proof",
                        },
                        "check_args": {},
                        "invocation_sha256": "0" * 64,
                    },
                    "fresh_replay": {
                        "schema_version": "ncf.producer-replay-verification.v1",
                        "status": "PASS",
                        "invocation_sha256": "0" * 64,
                        "output_sha256": "0" * 64,
                        "output_bytes": ledger_path.stat().st_size
                        + proof_path.stat().st_size,
                        "output_semantic_sha256": "0" * 64,
                        "network_control": (
                            "APPLICATION_SOCKET_GUARD_OFFLINE_NOT_OS_SANDBOX"
                        ),
                        "outputs": {
                            "ledger": {
                                "ref_id": "sanitized-ledger",
                                "sha256": self.ref(ledger_path)["sha256"],
                                "bytes": self.ref(ledger_path)["bytes"],
                                "semantic_sha256": "0" * 64,
                            },
                            "assignment_proof": {
                                "ref_id": "assignment-proof",
                                "sha256": self.ref(proof_path)["sha256"],
                                "bytes": self.ref(proof_path)["bytes"],
                                "semantic_sha256": "0" * 64,
                            },
                        },
                    },
                },
            )
        self.external_sanitized_ledger_artifact = ledger_artifact
        self.external_sanitized_assignment_proof_ref = self.ref(proof_path)
        self.external_sanitized_replay_verification_ref = self.ref(
            verification_path
        )

    def _external_sanitized_ledger_input(self) -> dict[str, Any]:
        return {
            **copy.deepcopy(self.external_sanitized_ledger_artifact),
            "producer": {
                "kind": "SEALED_EXECUTABLE_OUTPUT",
                "producer_id": "evaluator-sanitized-runtime-ledger-compiler-v1",
                "assignment_proof": copy.deepcopy(
                    self.external_sanitized_assignment_proof_ref
                ),
                "replay_verification": copy.deepcopy(
                    self.external_sanitized_replay_verification_ref
                ),
            },
        }

    def _create_role(self, role: str, role_index: int) -> None:
        policy = self.protocol["roles"][role]
        role_dir = self.root / "run" / role
        output_dir = role_dir / "outputs"
        output_dir.mkdir(parents=True, exist_ok=True)

        inputs: list[dict[str, Any]] = []
        for data_class in policy["allowed_input_data_classes"]:
            if data_class in self.root_classes:
                inputs.append(self._root_input(data_class))
            elif data_class == "evaluator_sanitized_runtime_ledger":
                inputs.append(self._external_sanitized_ledger_input())
            else:
                inputs.append(self._upstream_input(data_class))

        outputs: list[dict[str, Any]] = []
        source_event_payload, source_availability_payload = (
            self._source_ledgers_for_compiler()
        )
        for data_class in policy["allowed_output_data_classes"]:
            if data_class == "all_sealed_artifacts_after_replay":
                # This typed inventory is created after its sibling outputs so
                # that it can bind their exact content identities.
                continue
            path = output_dir / f"{data_class}.json"
            if data_class == "sealed_event_ledger":
                payload = source_event_payload
            elif data_class == "sealed_availability_ledger":
                payload = source_availability_payload
            elif data_class == "sealed_concept_map":
                mapping_is_action = self.sanitized_event_kind in {"ACTION", "SUPPORT"}
                mapping_unit = (
                    self.sanitized_unit
                    if self.sealed_mapping_unit_override is _UNSET
                    else self.sealed_mapping_unit_override
                )
                payload = {
                    "schema_version": "NCF-SEALED-CONCEPT-MAP-1.0.0",
                    "mappings": [
                        {
                            "opaque_source_concept_token": (
                                self.opaque_source_concept_token_override
                                or "SC-00000001"
                            ),
                            "mapped_id": (
                                "ACTION_FLUID_CHALLENGE"
                                if mapping_is_action
                                else "left_ventricular_ejection_fraction_percent"
                            ),
                            "entity_type": (
                                "ACTION" if mapping_is_action else "OBSERVATION"
                            ),
                            "value_type": "ACTION" if mapping_is_action else "NUMBER",
                            "unit": mapping_unit,
                            "mapping_status": "MAPPED",
                        }
                    ],
                }
            else:
                payload = {"role": role, "data_class": data_class, "ok": True}
            _write_json(path, payload)
            outputs.append(self.artifact(path, data_class))

        if "all_sealed_artifacts_after_replay" in policy["allowed_output_data_classes"]:
            path = output_dir / "all_sealed_artifacts_after_replay.json"
            inventory = [
                {
                    key: row[key]
                    for key in ("path", "sha256", "bytes", "data_class", "schema_id")
                }
                for row in [*inputs, *outputs]
                if row["data_class"] != self.omit_all_sealed_inventory_class
            ]
            _write_json(
                path,
                {
                    "schema_version": "NCF-ALL-SEALED-ARTIFACTS-AFTER-REPLAY-1.0.0",
                    "evaluator_run_id": f"fixture-{role}",
                    "replay_sealed": True,
                    "oracle_contents_included": False,
                    "artifacts": inventory,
                },
            )
            outputs.append(self.artifact(path, "all_sealed_artifacts_after_replay"))

        prompt = role_dir / "prompt.txt"
        prompt.write_text(f"frozen isolated prompt for {role}\n", encoding="utf-8")
        parent = role_dir / "parent_packet.json"
        _write_json(parent, {"role": role, "parent": "fixture-supervisor"})
        prompt_ref = self.ref(prompt)
        parent_ref = self.ref(parent)

        run_id = f"fixture-{role}"
        case_identity_exposed = policy["case_identity_exposure"] != "FORBIDDEN"
        scout_network = role == "scout"
        trace = {
            "schema_version": "NCF-PRIMARY-ROLE-TOOL-ACCESS-TRACE-1.0.0",
            "role": role,
            "run_id": run_id,
            "execution_kind": "SCRIPT",
            "case_identity_exposed": case_identity_exposed,
            "prompt_or_command_sha256": prompt_ref["sha256"],
            "parent_packet_sha256": parent_ref["sha256"],
            "tool_lineage": [
                {
                    "tool_id": "fixture.primary-role-runner",
                    "version_or_build": "1.0.0-test",
                    "invocation_id": f"invoke-{role}",
                }
            ],
            "accesses": self._trace_accesses(inputs, outputs, prompt_ref, parent_ref),
            "network_requests": (
                [
                    {
                        "sequence": 0,
                        "method": "GET",
                        "request_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pmc&term=fixture",
                        "response_sha256": "0" * 64,
                        "response_bytes": 1,
                        "retrieved_at": "2026-07-21T00:00:00+09:00",
                    }
                ]
                if scout_network
                else []
            ),
            "trace_complete": True,
            "undeclared_access_detected": False,
            "network_access_detected": scout_network,
        }
        trace_path = role_dir / "tool_access_trace.json"
        _write_json(trace_path, trace)

        start = datetime(2026, 7, 21, tzinfo=timezone(timedelta(hours=9))) + timedelta(
            minutes=role_index * 3
        )
        manifest = {
            "schema_version": "NCF-PRIMARY-ROLE-MANIFEST-1.1.0",
            "role": role,
            "run_id": run_id,
            "started_at": start.isoformat(),
            "finished_at": (start + timedelta(minutes=1)).isoformat(),
            "case_identity_exposed": case_identity_exposed,
            "inputs": inputs,
            "outputs": outputs,
            "observed_data_classes": list(policy["allowed_input_data_classes"]),
            "attestations": {
                "only_declared_inputs_observed": True,
                "no_forbidden_data_class_observed": True,
                "no_undeclared_output_written": True,
                "no_artifact_modified_after_input_hash": True,
            },
            "prompt_or_command": prompt_ref,
            "tool_trace": self.ref(trace_path),
            "parent_packet": parent_ref,
        }
        manifest_path = role_dir / "role_execution_manifest.json"
        _write_json(manifest_path, manifest)
        self.manifest_paths[role] = manifest_path

        for output in outputs:
            self.output_by_class[output["data_class"]] = {
                "role": role,
                "run_id": run_id,
                "artifact": copy.deepcopy(output),
                "manifest_path": manifest_path,
            }

    def _create_complete_role_dag(self) -> None:
        for index, role in enumerate(self.roles):
            self._create_role(role, index)
            if role == "concept_mapper":
                self._create_external_sanitized_ledger()
        aggregate = {
            "schema_version": "NCF-PRIMARY-ROLE-MANIFEST-SET-1.0.0",
            "protocol": self.ref(self.protocol_path),
            "manifests": [],
        }
        for role in self.roles:
            manifest = self.read_json(self.manifest_paths[role])
            aggregate["manifests"].append(
                {
                    "role": role,
                    "run_id": manifest["run_id"],
                    **self.ref(self.manifest_paths[role]),
                }
            )
        _write_json(self.aggregate_path, aggregate)

    def manifest(self, role: str) -> dict[str, Any]:
        return self.read_json(self.manifest_paths[role])

    def write_manifest(self, role: str, value: Mapping[str, Any]) -> None:
        _write_json(self.manifest_paths[role], value)

    def trace_path(self, role: str) -> Path:
        manifest = self.manifest(role)
        return self.root / manifest["tool_trace"]["path"]

    def trace(self, role: str) -> dict[str, Any]:
        return self.read_json(self.trace_path(role))

    def write_trace_and_rebind_manifest(
        self, role: str, trace: Mapping[str, Any]
    ) -> None:
        trace_path = self.trace_path(role)
        _write_json(trace_path, trace)
        manifest = self.manifest(role)
        manifest["tool_trace"] = self.ref(trace_path)
        self.write_manifest(role, manifest)

    def refresh_aggregate_manifest_ref(self, role: str) -> None:
        aggregate = self.read_json(self.aggregate_path)
        row = next(item for item in aggregate["manifests"] if item["role"] == role)
        fresh = self.ref(self.manifest_paths[role])
        row.update(fresh)
        _write_json(self.aggregate_path, aggregate)

    def replace_input_content_ref(
        self, role: str, data_class: str, fresh_ref: Mapping[str, Any]
    ) -> None:
        manifest = self.manifest(role)
        input_row = next(row for row in manifest["inputs"] if row["data_class"] == data_class)
        for key in ("path", "sha256", "bytes"):
            input_row[key] = fresh_ref[key]
        trace_path = self.root / manifest["tool_trace"]["path"]
        trace = self.read_json(trace_path)
        access = next(
            row
            for row in trace["accesses"]
            if row["artifact_kind"] == "INPUT" and row["data_class"] == data_class
        )
        for key in ("path", "sha256", "bytes"):
            access[key] = fresh_ref[key]
        _write_json(trace_path, trace)
        manifest["tool_trace"] = self.ref(trace_path)
        self.write_manifest(role, manifest)

    def assignment_proof_path(self) -> Path:
        evaluator = self.manifest("evaluator")
        ledger_input = next(
            row
            for row in evaluator["inputs"]
            if row["data_class"] == "evaluator_sanitized_runtime_ledger"
        )
        return self.root / ledger_input["producer"]["assignment_proof"]["path"]

    def assignment_proof(self) -> dict[str, Any]:
        return self.read_json(self.assignment_proof_path())

    def replay_verification_path(self) -> Path:
        evaluator = self.manifest("evaluator")
        ledger_input = next(
            row
            for row in evaluator["inputs"]
            if row["data_class"] == "evaluator_sanitized_runtime_ledger"
        )
        return self.root / ledger_input["producer"]["replay_verification"]["path"]

    def replay_verification(self) -> dict[str, Any]:
        return self.read_json(self.replay_verification_path())

    def write_replay_verification_and_rebind_evaluator(
        self, verification: Mapping[str, Any]
    ) -> None:
        verification_path = self.replay_verification_path()
        _write_json(verification_path, verification)
        evaluator = self.manifest("evaluator")
        ledger_input = next(
            row
            for row in evaluator["inputs"]
            if row["data_class"] == "evaluator_sanitized_runtime_ledger"
        )
        ledger_input["producer"]["replay_verification"] = self.ref(
            verification_path
        )
        self.write_manifest("evaluator", evaluator)

    def write_assignment_proof_and_rebind_evaluator(
        self, proof: Mapping[str, Any]
    ) -> None:
        proof_path = self.assignment_proof_path()
        _write_json(proof_path, proof)
        evaluator = self.manifest("evaluator")
        ledger_input = next(
            row
            for row in evaluator["inputs"]
            if row["data_class"] == "evaluator_sanitized_runtime_ledger"
        )
        ledger_input["producer"]["assignment_proof"] = self.ref(proof_path)
        self.write_manifest("evaluator", evaluator)

    def regenerate_replay_verification_and_rebind_evaluator(self) -> None:
        evaluator = self.manifest("evaluator")
        ledger_input = next(
            row
            for row in evaluator["inputs"]
            if row["data_class"] == "evaluator_sanitized_runtime_ledger"
        )
        proof_path = self.root / ledger_input["producer"]["assignment_proof"]["path"]
        proof = self.read_json(proof_path)
        manifest_path = self.root / proof["input_manifest"]["path"]
        verification_path = (
            self.root / ledger_input["producer"]["replay_verification"]["path"]
        )
        verification_path.unlink(missing_ok=True)
        completed = subprocess.run(
            [
                sys.executable,
                str(self.root / SANITIZED_REPLAY_VERIFIER_REL),
                "verify",
                "--study-root",
                str(self.root),
                "--manifest",
                str(manifest_path),
                "--ledger",
                str(self.root / ledger_input["path"]),
                "--assignment-proof",
                str(proof_path),
                "--combined-seal",
                str(self.root / self.root_paths["combined_preprimary_seal"]),
                "--output",
                str(verification_path),
            ],
            cwd=self.root,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        if completed.returncode != 0:
            raise AssertionError(
                "failed to regenerate sanitizer replay verification: "
                f"stdout={completed.stdout!r} stderr={completed.stderr!r}"
            )
        ledger_input["producer"]["replay_verification"] = self.ref(
            verification_path
        )
        self.write_manifest("evaluator", evaluator)


class PrimaryRoleManifestContractHardeningTests(unittest.TestCase):
    def fixture(self, temp: str) -> _RoleContractFixture:
        return _RoleContractFixture(Path(temp))

    def test_complete_exact_role_dag_passes(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            result = validate_role_manifest_set(fixture.root, fixture.aggregate_path)
            self.assertEqual(result["status"], "PASS")
            self.assertEqual(result["role_count"], 8)

    def test_evaluator_has_exact_ninth_combined_seal_root_binding(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            evaluator = fixture.manifest("evaluator")
            self.assertEqual(len(evaluator["inputs"]), 9)
            row = next(
                item
                for item in evaluator["inputs"]
                if item["data_class"] == "combined_preprimary_seal"
            )
            self.assertEqual(
                {
                    key: row[key]
                    for key in ("path", "sha256", "bytes")
                },
                fixture.seal_ref,
            )
            self.assertEqual(row["schema_id"], "ncf.data.combined-preprimary-seal.v1")
            self.assertEqual(
                row["producer"],
                {"kind": "PRESEALED_ROOT", "seal": fixture.seal_ref},
            )

    def test_sanitized_ledger_is_external_compiler_output_not_role_output(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            source_auditor = fixture.manifest("source_auditor")
            self.assertNotIn(
                "evaluator_sanitized_runtime_ledger",
                {row["data_class"] for row in source_auditor["outputs"]},
            )
            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            self.assertEqual(
                ledger_input["producer"]["kind"], "SEALED_EXECUTABLE_OUTPUT"
            )
            self.assertEqual(
                ledger_input["producer"]["producer_id"],
                "evaluator-sanitized-runtime-ledger-compiler-v1",
            )

    def test_sanitized_ledger_presealed_root_spoof_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            ledger_input["producer"] = {
                "kind": "PRESEALED_ROOT",
                "seal": fixture.seal_ref,
            }
            fixture.write_manifest("evaluator", evaluator)
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_ledger_assignment_digest_mutation_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            proof = fixture.assignment_proof()
            proof["assignment_digest"] = "f" * 64
            fixture.write_assignment_proof_and_rebind_evaluator(proof)
            with self.assertRaisesRegex(ProtocolError, "proof digest mismatch"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_ledger_missing_replay_verification_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            ledger_input["producer"].pop("replay_verification")
            fixture.write_manifest("evaluator", evaluator)
            with self.assertRaisesRegex(
                ProtocolError, "invalid SEALED_EXECUTABLE_OUTPUT input"
            ):
                validate_role_manifest(
                    fixture.root, fixture.manifest_paths["evaluator"]
                )

    def test_forged_sanitized_replay_verification_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            verification = fixture.replay_verification()
            verification["replay_policy_sha256"] = "f" * 64
            fixture.write_replay_verification_and_rebind_evaluator(verification)
            with self.assertRaisesRegex(
                ProtocolError, "forged, stale, or not the exact fresh-replay result"
            ):
                validate_role_manifest(
                    fixture.root, fixture.manifest_paths["evaluator"]
                )

    def test_rehashed_noncompiler_ledger_is_rejected_by_fresh_replay(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            ledger_path = fixture.root / ledger_input["path"]
            ledger = fixture.read_json(ledger_path)
            ledger["events"][0]["typed_value"]["canonical"] = "2"
            _write_json(ledger_path, ledger)
            fresh_ledger_ref = fixture.ref(ledger_path)
            for key in ("sha256", "bytes"):
                ledger_input[key] = fresh_ledger_ref[key]
            fixture.write_manifest("evaluator", evaluator)

            proof = fixture.assignment_proof()
            proof["output_ledger"].update(
                {
                    "sha256": fresh_ledger_ref["sha256"],
                    "bytes": fresh_ledger_ref["bytes"],
                }
            )
            fixture.write_assignment_proof_and_rebind_evaluator(proof)

            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            verification = fixture.replay_verification()
            verification["compiler_outputs"]["ledger"] = fixture.ref(ledger_path)
            verification["compiler_outputs"]["assignment_proof"] = copy.deepcopy(
                ledger_input["producer"]["assignment_proof"]
            )
            fixture.write_replay_verification_and_rebind_evaluator(verification)
            with self.assertRaisesRegex(
                ProtocolError, "compiler exact fresh replay failed"
            ):
                validate_role_manifest(
                    fixture.root, fixture.manifest_paths["evaluator"]
                )

    def test_sanitized_ledger_actual_path_basename_substitution_is_rejected(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            evaluator = fixture.manifest("evaluator")
            ledger_input = next(
                row
                for row in evaluator["inputs"]
                if row["data_class"] == "evaluator_sanitized_runtime_ledger"
            )
            original = fixture.root / ledger_input["path"]
            substituted = original.with_name("substituted_ledger.json")
            substituted.write_bytes(original.read_bytes())
            ledger_input.update(fixture.ref(substituted))
            fixture.write_manifest("evaluator", evaluator)
            with self.assertRaisesRegex(
                ProtocolError, "does not use frozen logical basename"
            ):
                validate_role_manifest(
                    fixture.root, fixture.manifest_paths["evaluator"]
                )

    def test_sanitizer_proof_cannot_substitute_nonrole_upstream_artifact(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            proof = fixture.assignment_proof()
            manifest_path = fixture.root / proof["input_manifest"]["path"]
            compiler_manifest = fixture.read_json(manifest_path)
            original = fixture.root / compiler_manifest["inputs"]["sealed_event_ledger"]["path"]
            substituted = fixture.root / "run/external_sanitizer/substituted_event_ledger.json"
            substituted.write_bytes(original.read_bytes())
            replacement = {
                **fixture.ref(substituted),
                "data_class": "sealed_event_ledger",
                "schema_id": "ncf.data.sealed-event-ledger.v1",
            }
            compiler_manifest["inputs"]["sealed_event_ledger"] = replacement
            _write_json(manifest_path, compiler_manifest)
            proof["input_manifest"] = fixture.ref(manifest_path)
            proof_row = next(
                row for row in proof["inputs"] if row["slot"] == "sealed_event_ledger"
            )
            proof_row.update(replacement)
            fixture.write_assignment_proof_and_rebind_evaluator(proof)
            scorer = fixture.manifest("scorer_auditor")
            fresh_evaluator_manifest = fixture.ref(
                fixture.manifest_paths["evaluator"]
            )
            for row in scorer["inputs"]:
                producer = row["producer"]
                if (
                    producer["kind"] == "ROLE_OUTPUT"
                    and producer["role"] == "evaluator"
                ):
                    producer["manifest_path"] = fresh_evaluator_manifest["path"]
                    producer["manifest_sha256"] = fresh_evaluator_manifest["sha256"]
                    producer["manifest_bytes"] = fresh_evaluator_manifest["bytes"]
            fixture.write_manifest("scorer_auditor", scorer)
            fixture.refresh_aggregate_manifest_ref("evaluator")
            fixture.refresh_aggregate_manifest_ref("scorer_auditor")
            with self.assertRaisesRegex(
                ProtocolError,
                "replay verification does not bind exact evaluator ledger and assignment proof",
            ):
                validate_role_manifest_set(fixture.root, fixture.aggregate_path)

    def test_role_dag_has_no_role_generated_final_scoring_loop(self) -> None:
        removed = {
            "case_evaluation",
            "candidate_report",
            "report_consistency",
            "scoring_output",
            "final_result",
        }
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            scorer = fixture.manifest("scorer_auditor")
            self.assertEqual(
                {row["data_class"] for row in scorer["outputs"]}, {"audit_report"}
            )
            self.assertTrue(removed.isdisjoint(fixture.schema_ids))
            for role in fixture.roles:
                self.assertTrue(
                    removed.isdisjoint(
                        row["data_class"] for row in fixture.manifest(role)["outputs"]
                    )
                )

    def test_arbitrary_presealed_root_spoof_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            spoof = fixture.root / "spoof/broad_scope.md"
            spoof.parent.mkdir(parents=True)
            spoof.write_text("# spoof root\n", encoding="utf-8")
            fixture.replace_input_content_ref("scout", "broad_scope", fixture.ref(spoof))
            with self.assertRaisesRegex(ProtocolError, "PRESEALED_ROOT path mismatch"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_exact_root_tuple_absent_from_bound_combined_seal_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            broad_scope = fixture.root / fixture.root_paths["broad_scope"]
            broad_scope.write_text("# mutated after the mock seal\n", encoding="utf-8")
            fixture.replace_input_content_ref("scout", "broad_scope", fixture.ref(broad_scope))
            with self.assertRaisesRegex(ProtocolError, "absent from the bound combined seal"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_hollow_trace_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            fixture.write_trace_and_rebind_manifest("scout", {"ok": True})
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_undeclared_trace_access_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            trace = fixture.trace("scout")
            extra = copy.deepcopy(trace["accesses"][0])
            extra.update(
                {
                    "sequence": len(trace["accesses"]),
                    "data_class": "oracle_contents",
                    "schema_id": fixture.schema_ids["oracle_contents"],
                }
            )
            trace["accesses"].append(extra)
            fixture.write_trace_and_rebind_manifest("scout", trace)
            with self.assertRaisesRegex(ProtocolError, "tool access trace is not exact"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_missing_required_input_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            manifest = fixture.manifest("scout")
            manifest["inputs"].pop()
            fixture.write_manifest("scout", manifest)
            with self.assertRaisesRegex(ProtocolError, "inputs must contain every frozen allowed class"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_missing_required_output_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            manifest = fixture.manifest("scout")
            manifest["outputs"].pop()
            fixture.write_manifest("scout", manifest)
            with self.assertRaisesRegex(ProtocolError, "outputs must contain every frozen allowed class"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_role_output_without_manifest_bytes_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            manifest = fixture.manifest("screener")
            row = next(
                item for item in manifest["inputs"] if item["producer"]["kind"] == "ROLE_OUTPUT"
            )
            row["producer"].pop("manifest_bytes")
            fixture.write_manifest("screener", manifest)
            with self.assertRaisesRegex(ProtocolError, "producer lineage is incomplete"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["screener"])

    def test_manifest_set_missing_role_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            aggregate = fixture.read_json(fixture.aggregate_path)
            aggregate["manifests"].pop()
            _write_json(fixture.aggregate_path, aggregate)
            with self.assertRaises(ProtocolError):
                validate_role_manifest_set(fixture.root, fixture.aggregate_path)

    def test_manifest_set_missing_mandatory_edge_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            manifest = fixture.manifest("scorer_auditor")
            manifest["inputs"] = [
                row
                for row in manifest["inputs"]
                if row["data_class"] != "mapped_observation_consumption"
            ]
            fixture.write_manifest("scorer_auditor", manifest)
            fixture.refresh_aggregate_manifest_ref("scorer_auditor")
            with self.assertRaisesRegex(ProtocolError, "inputs must contain every frozen allowed class"):
                validate_role_manifest_set(fixture.root, fixture.aggregate_path)

    def test_producer_consumer_timing_violation_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            manifest = fixture.manifest("scorer_auditor")
            manifest["started_at"] = "2026-07-21T00:00:00+09:00"
            manifest["finished_at"] = "2026-07-21T00:30:00+09:00"
            fixture.write_manifest("scorer_auditor", manifest)
            fixture.refresh_aggregate_manifest_ref("scorer_auditor")
            with self.assertRaisesRegex(ProtocolError, "started before producer"):
                validate_role_manifest_set(fixture.root, fixture.aggregate_path)

    def test_nested_attestation_schema_weakening_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            schema_path = fixture.root / ROLE_SCHEMA_REL
            schema = fixture.read_json(schema_path)
            schema["properties"]["attestations"]["properties"][
                "only_declared_inputs_observed"
            ].pop("const")
            _write_json(schema_path, schema)
            with self.assertRaisesRegex(ProtocolError, "attestation const weakened"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_network_response_byte_schema_weakening_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            schema_path = fixture.root / TRACE_SCHEMA_REL
            schema = fixture.read_json(schema_path)
            schema["$defs"]["networkRequest"]["properties"]["response_bytes"][
                "minimum"
            ] = 0
            _write_json(schema_path, schema)
            with self.assertRaisesRegex(
                ProtocolError, "network response byte constraint weakened"
            ):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_role_deletion_from_nested_schema_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = self.fixture(temp)
            schema_path = fixture.root / ROLE_SCHEMA_REL
            schema = fixture.read_json(schema_path)
            schema["$defs"]["role"]["enum"].remove("scorer_auditor")
            _write_json(schema_path, schema)
            with self.assertRaisesRegex(ProtocolError, "exact required role set"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["scout"])

    def test_sanitized_unit_object_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), sanitized_unit={"free_text": "percent"}
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_unit_free_text_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), sanitized_unit="patient-specific free text"
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_legacy_absolute_datetime_fields_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(Path(temp), use_legacy_absolute_times=True)
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_action_without_lifecycle_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), sanitized_event_kind="ACTION", include_action_lifecycle=False
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_with_lifecycle_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="OBSERVATION",
                include_action_lifecycle=True,
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_arbitrary_code_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), malicious_sanitized_canonical="PMID12345678"
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_reversible_source_identifier_field_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), sanitized_ledger_extra={"pmid": "PMID: 12345678"}
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_availability_before_observation_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), observed_epoch_ordinal=2, available_epoch_ordinal=1
            )
            with self.assertRaisesRegex(ProtocolError, "availability precedes observation"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_missing_one_qualification_field_is_rejected(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                omit_evidence_qualification_field="adequate_timing",
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_invalid_tristate_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                evidence_qualification_override={"adequate_method": "YES"},
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_missing_alternative_group_field_is_rejected(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), include_alternative_representation_group=False
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_invalid_alternative_group_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), alternative_representation_group_id="same-result"
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_observation_valid_alternative_group_passes(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                alternative_representation_group_id="ARG-00000001",
            )
            result = validate_role_manifest(
                fixture.root, fixture.manifest_paths["evaluator"]
            )
            self.assertEqual(result["status"], "PASS")

    def test_sanitized_run_id_not_derived_from_combined_seal_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), opaque_run_id_override=f"RUN-{'f' * 64}"
            )
            with self.assertRaisesRegex(ProtocolError, "combined-seal/run binding mismatch"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_noncanonical_event_sequence_id_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), opaque_event_id_override="EV-00000002"
            )
            with self.assertRaisesRegex(ProtocolError, "one-based row ids"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_noncanonical_source_concept_id_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), opaque_source_concept_token_override="SC-00000002"
            )
            with self.assertRaisesRegex(ProtocolError, "mapper-row ids"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_noncanonical_action_first_occurrence_id_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                opaque_action_id_override="ACT-00000002",
            )
            with self.assertRaisesRegex(ProtocolError, "first-occurrence ids"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_noncanonical_alternative_group_first_occurrence_is_rejected(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), alternative_representation_group_id="ARG-00000002"
            )
            with self.assertRaisesRegex(ProtocolError, "first-occurrence ids"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_action_valid_lifecycle_sequence_passes(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                action_lifecycle_sequence=[
                    (0, "ORDERED"),
                    (1, "STARTED"),
                    (2, "CONTINUED"),
                    (3, "DOSE_CHANGED"),
                    (4, "HELD"),
                    (5, "RESUMED"),
                    (6, "COMPLETED"),
                ],
            )
            result = validate_role_manifest(
                fixture.root, fixture.manifest_paths["evaluator"]
            )
            self.assertEqual(result["status"], "PASS")

    def test_sanitized_action_illegal_lifecycle_transition_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                action_lifecycle_sequence=[(0, "STARTED"), (1, "RESUMED")],
            )
            with self.assertRaisesRegex(ProtocolError, "transition is illegal"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_author_washout_phase_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="WASHOUT",
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_author_active_alias_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="ACTIVE",
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_started_action_missing_dose_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="STARTED",
                omit_action_dose_fields=True,
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_held_action_carrying_dose_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="HELD",
                force_action_dose_fields=True,
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_action_free_text_dose_unit_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="STARTED",
                action_dose_unit="mg/kg free text",
            )
            with self.assertRaises(ProtocolError):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sanitized_action_dose_above_model_reference_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp),
                sanitized_event_kind="ACTION",
                include_action_lifecycle=True,
                action_lifecycle_phase="STARTED",
                action_dose_canonical="1.0001",
            )
            with self.assertRaisesRegex(ProtocolError, "exceeds frozen model reference"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_sealed_concept_map_registry_mismatch_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), sealed_mapping_unit_override="mmHg"
            )
            with self.assertRaisesRegex(
                ProtocolError, "does not exactly bind sanitized registry"
            ):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])

    def test_all_sealed_inventory_missing_runtime_output_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            fixture = _RoleContractFixture(
                Path(temp), omit_all_sealed_inventory_class="runtime_output"
            )
            with self.assertRaisesRegex(ProtocolError, "inventory is not exact"):
                validate_role_manifest(fixture.root, fixture.manifest_paths["evaluator"])


if __name__ == "__main__":
    unittest.main()
